plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

version = project.mod_version
group = 'com.feisk73'

base {
	archivesName = 'nobedrock'
}

repositories {
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 21
}

tasks.processResources {
	inputs.property 'version', project.version
	filesMatching('fabric.mod.json') {
		expand version: project.version
	}
}

tasks.named('remapJar') {
	archiveFileName = 'nobedrock-1.0-SNAPSHOT.jar'
	destinationDirectory = file('..')
}
