# https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes
# use data from "Name" column
outlineColor=white

# Radius from player where item frames are glowing ("-1" to disable)
radiusOfGlowing=-1

# If true, frames will glow for individual players based on radius
clientSideGlowing=true

# Do shears get damaged and break
doShearsBreak=true

# True if you want to reverse invisible frames back with leather
fixWithLeather=true